// src/theme/themePresets.ts
import type { ThemeSettings } from "./themeSettings.types";

export interface ThemePresetDefinition {
  id: string;
  name: string;
  description: string;
  /** Deux couleurs hex pour l'aperçu en dégradé */
  swatch: [string, string];
  settings: Partial<ThemeSettings>;
}

export const themePresets: ThemePresetDefinition[] = [
  {
    id: "macos",
    name: "macOS",
    description: "Épuré, compact, bleu système",
    swatch: ["#228be6", "#15aabf"],
    settings: {
      colorScheme: "auto",
      primaryColor: "blue",
      radius: "sm",
      scale: "sm",
      fontFamily: "system",
      headingFontFamily: "system",
      shadowIntensity: "flat",
      letterSpacing: "tight",
      autoContrast: true,
      cursorType: "default",
      gradientFrom: "blue",
      gradientTo: "cyan",
    },
  },
  {
    id: "slate",
    name: "Ardoise",
    description: "Minimaliste, monochrome",
    swatch: ["#495057", "#868e96"],
    settings: {
      colorScheme: "light",
      primaryColor: "gray",
      radius: "xs",
      scale: "sm",
      fontFamily: "system",
      headingFontFamily: "system",
      shadowIntensity: "flat",
      letterSpacing: "normal",
      autoContrast: true,
      cursorType: "default",
      gradientFrom: "gray",
      gradientTo: "gray",
    },
  },
  {
    id: "ocean",
    name: "Océan",
    description: "Frais et lisible, bleu-sarcelle",
    swatch: ["#15aabf", "#12b886"],
    settings: {
      colorScheme: "auto",
      primaryColor: "cyan",
      radius: "md",
      scale: "md",
      fontFamily: "inter",
      headingFontFamily: "inter",
      shadowIntensity: "subtle",
      letterSpacing: "normal",
      autoContrast: true,
      cursorType: "pointer",
      gradientFrom: "cyan",
      gradientTo: "teal",
    },
  },
  {
    id: "sunset",
    name: "Coucher de soleil",
    description: "Chaleureux et énergique",
    swatch: ["#fd7e14", "#fa5252"],
    settings: {
      colorScheme: "light",
      primaryColor: "orange",
      radius: "lg",
      scale: "md",
      fontFamily: "poppins",
      headingFontFamily: "poppins",
      shadowIntensity: "elevated",
      letterSpacing: "normal",
      autoContrast: true,
      cursorType: "pointer",
      gradientFrom: "orange",
      gradientTo: "red",
    },
  },
  {
    id: "forest",
    name: "Forêt",
    description: "Naturel et apaisant",
    swatch: ["#40c057", "#12b886"],
    settings: {
      colorScheme: "auto",
      primaryColor: "green",
      radius: "md",
      scale: "md",
      fontFamily: "system",
      headingFontFamily: "system",
      shadowIntensity: "subtle",
      letterSpacing: "normal",
      autoContrast: true,
      cursorType: "pointer",
      gradientFrom: "green",
      gradientTo: "teal",
    },
  },
  {
    id: "candy",
    name: "Candy",
    description: "Ludique et coloré",
    swatch: ["#7950f2", "#e64980"],
    settings: {
      colorScheme: "light",
      primaryColor: "violet",
      radius: "xl",
      scale: "md",
      fontFamily: "poppins",
      headingFontFamily: "poppins",
      shadowIntensity: "elevated",
      letterSpacing: "relaxed",
      autoContrast: true,
      cursorType: "pointer",
      gradientFrom: "violet",
      gradientTo: "pink",
    },
  },
  {
    id: "corporate",
    name: "Corporate",
    description: "Sobre et professionnel",
    swatch: ["#4c6ef5", "#495057"],
    settings: {
      colorScheme: "light",
      primaryColor: "indigo",
      radius: "sm",
      scale: "sm",
      fontFamily: "roboto",
      headingFontFamily: "roboto",
      shadowIntensity: "flat",
      letterSpacing: "tight",
      autoContrast: true,
      cursorType: "default",
      gradientFrom: "indigo",
      gradientTo: "gray",
    },
  },
  {
    id: "midnight",
    name: "Minuit",
    description: "Sombre et élégant",
    swatch: ["#4c6ef5", "#7950f2"],
    settings: {
      colorScheme: "dark",
      primaryColor: "indigo",
      radius: "md",
      scale: "md",
      fontFamily: "inter",
      headingFontFamily: "inter",
      shadowIntensity: "elevated",
      letterSpacing: "normal",
      autoContrast: true,
      cursorType: "pointer",
      gradientFrom: "indigo",
      gradientTo: "violet",
    },
  },
];
